version: "3.7"

services:
  
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    ports:
      - "7600:7600"
    networks:
      - app-network
    env_file:
      - .env
    restart: always
    


networks:
  app-network:
    driver: bridge
    